name: solidcog-py39
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
dependencies:
  - python=3.9.13
  - pip
  - numpy=1.24.4
  - opencv=4.6.0
  - pillow=10.4.0
  - poppler
